apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: mesh-prom
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      timeInterval: 5s
    isDefault: true
    editable: false
