global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'gateway'
    metrics_path: /omnirelay/metrics
    static_configs:
      - targets: ['gateway:5080']

  - job_name: 'inventory'
    metrics_path: /omnirelay/metrics
    static_configs:
      - targets: ['inventory-primary:6080', 'inventory-secondary:6080']

  - job_name: 'audit'
    metrics_path: /omnirelay/metrics
    static_configs:
      - targets: ['audit:6080']
